### ISSUE TITLE
Update entrygroups (PUT, DELETE) endoints to API v2 

### ISSUE THREAD

**Issue by meaku** [peerigon/clockodo#107]
The `editEntryGroup` and `deleteEntryGroup` calls still point to the – non existing – v1 endpoint. 
The endpoint needs to be adjust to `/v2`: 

- https://github.com/peerigon/clockodo/blob/main/src/clockodo.ts#L506
- https://github.com/peerigon/clockodo/blob/main/src/clockodo.ts#L614

**Comment by jannikkeye** [comment]
This also blocks dashboard refactoring efforts: https://github.com/peerigon/dashboard/pull/84

@jhnns does it take more than just updating the url? Or did the api change in any way?
