### ISSUE TITLE
Reconsider Method Parameters

### ISSUE THREAD

**Issue by THoisington** [peerigon/clockodo#13]
Currently with some endpoint methods that have a required ID, we have it as a separate argument from the typical object passed in with all the other parameters(required or not). Example: 

![separate](https://user-images.githubusercontent.com/1280597/42578183-53aafc2e-8526-11e8-8103-f5e5f27d15ac.png)

However, others with required parameters are lumped together in a single object:

![object](https://user-images.githubusercontent.com/1280597/42578464-c8c33026-8526-11e8-8d67-f89f0a5d4ecc.png)

Should we make required parameters separate, or keep them as is?

**Comment by THoisington** [comment]
So it looks like we are going forward with this implementation (with different jsdoc) 

![code](https://user-images.githubusercontent.com/1280597/44723353-05addd00-aad0-11e8-8d4b-03171c049b11.png)

@meaku

**Comment by meaku** [comment]
Sweet! 🍍
