### ISSUE TITLE
Find Solution for JSDOC with destructured function params. 

### ISSUE THREAD

**Issue by tannerbaum** [peerigon/clockodo#15]
I documented the time I have spent trying to figure this out elsewhere on Github:
https://github.com/Microsoft/TypeScript/issues/24746#issuecomment-422051095

We made decide in the end it isn't even necessary, but I feel I am one step away from having the Intellisense so useful that there would be no need for the user of this API to leave their editor. But it shouldn't hold up the conversion to Typescript.

**Comment by aubcel** [comment]
@tannerbaum is this solved?

**Comment by jhnns** [comment]
We're using TypeScript for quite some time now 🎉
