### ISSUE TITLE
Introduce optional caching fo requests

### ISSUE THREAD

**Issue by aubcel** [peerigon/clockodo#44]
The Clockodo Api has some very expencive requests e.g. `getUserReport`.
In `Checkodo` there are multiple functions using these expensive requests.
This results in multiple simliar requests for loading the dashboard for example. To reduce these redundant requests it would be good to add an optional cache behavior to the `Clockodo SDK`

Creating a Clockodo instance with cache should look like that:
```
const clockodo = new Clockodo({
    apiKey: "key",
    user: "usermail",
    cacheTime: 15 * 60 * 1000      //time of the cache in ms, here it would be 15 minutes
});
```

* The chache entry is valid as long as there wasn't a `PUT`, `POST`, `PATCH` or `DELETE` request to the same url.
* When one of those requests is made or the time is over there will be made a new request which response will be stored in the cache again.
* If the instance is created without `cacheTime` it should behave the same as before.

**Comment by jhnns** [comment]
done()
