### ISSUE TITLE
Use semantic-release for publishing

### ISSUE THREAD

**Issue by jhnns** [peerigon/clockodo#47]
Based on the configuration of https://github.com/peerigon/eslint-config-peerigon (see https://github.com/peerigon/eslint-config-peerigon/blob/master/.github/workflows/release.yml)

**Comment by jannikkeye** [comment]
remember to install dependencies before the publishing step so the release assets can be built. Currently have the problem in extract-loader that no build step was executed in prePublishOnly so we have broken releases.

**Comment by jhnns** [comment]
https://github.com/peerigon/extract-loader/blob/master/.github/workflows/release.yml is a good blueprint

**Comment by jhnns** [comment]
done()
