### ISSUE TITLE
Async methods should not throw

### ISSUE THREAD

**Issue by jhnns** [peerigon/clockodo#8]
It's good practice that async methods (`async function` or functions that return a promise) do never throw. They should reject the promise. Otherwise, it leaves the consumers of our lib in a situation where they need to do things like:

```js
try {
clockodo
    .doSomething()
    .then(continueSomething)
    .catch(console.error); // catch the async error
} catch (err) {
    console.error(err); // also catch the sync error
}
```

You get the gist :)

Since we don't have async functions in our `api.js` and we're throwing on [`_checkRequired`](https://github.com/peerigon/clockodo/blob/master/src/api.js#L61), our API wrapper will throw an error (instead of rejecting the promise).

Could you rewrite the methods to async functions instead? Async functions reject the promise automatically. The refactoring shouldn't be very hard.

**Comment by THoisington** [comment]
![doh](https://user-images.githubusercontent.com/1280597/39187222-ff354730-47cc-11e8-9a3d-aa4acfc8ec35.jpg)

Will work on this.
